### ISSUE TITLE
Remove StAX dependency

### ISSUE THREAD

**Issue by runeflobakk** [jettison-json/jettison#20]
As Jettison itself [requires Java 1.6](https://github.com/jettison-json/jettison/blob/master/pom.xml#L58-L59), can the dependency on StAX be [removed](https://github.com/jettison-json/jettison/blob/master/pom.xml#L23-L27), as it is included in the JDK from version 1.6? Not a huge deal, but should be a quick win for some dependency housekeeping :)

We exclude stax-api when depending on Jettison, and everything works.

**Comment by dkulp** [comment]
Fixed in a10ed33510ab90bff0d3b967317ad62a64081d6d
