### ISSUE TITLE
method JSONObject.write() bug in case of ignored elements

### ISSUE THREAD

**Issue by deadlious** [jettison-json/jettison#35]
Hello fellow programmers,

I'm using the jettison library in a project and I stumbled upon a strange case when using the ignored elements in a Mapped convention.
When I try to ignore an element which is somewhere in the middle of an xml, the result JSON contains two commas in a row (",,"), which results in an invalid JSON structure.
I've debugged the library and it appears that in method JSONObject.write() the flag "b" is never reset to "false" inside the while loop.

**current snippet of code:**
```
 while (keys.hasNext()) {
                if (b) {
                    writer.write(',');
                }
```

**Suggested  change:**
```
 while (keys.hasNext()) {
                if (b) {
                    writer.write(',');
                    b = false;
                }
```

Would you please fix it and provide a new release?

**Comment by vlveselinov** [comment]
@cowtowncoder could you please check if this fix is correct and if it can be included in the official release?
Thank you in advance.

**Comment by cowtowncoder** [comment]
@vlveselinov you probably meant to tag someone else: I don't work on this project.

**Comment by vlveselinov** [comment]
@dkulp  could you please check if this fix is correct and if it can be included in the official release? I was mistaken that @cowtowncoder is contributing to this project, sorry about that.
Thank you in advance.
