### ISSUE TITLE
Need more check for JSONArray init, bad string can cause infinite loop

### ISSUE THREAD

**Issue by manecocomph** [jettison-json/jettison#36]
please debug below code, it will burn one CPU, and stuck on JSONTokener L179 ~ 188 -> next() -> back() -> next()

<pre>
public static void main(String[] args) {
		String str = "[*/*A25] **";
		try {
			System.out.println("start");
			System.out.println(new JSONArray(str));
			System.out.println("end");
		} catch (JSONException e) {
			e.printStackTrace();
		}
	}
</pre>

**Comment by lcoller** [comment]
Anyone fixing this issue?
