### ISSUE TITLE
Integrating jettison into OSS-Fuzz

### ISSUE THREAD

**Issue by vargen** [jettison-json/jettison#40]
Hi all,

I have prepared the integration [CodeIntelligenceTesting/oss-fuzz@d1c2376](https://github.com/CodeIntelligenceTesting/oss-fuzz/commit/d1c2376c6de58f1f03da8a19c23d99f005c28348) of jettison into google oss-fuzz. This will enable continuous fuzzing of this project, which will be conducted by Google. Bugs that will be found by fuzzing will be reported to you.

The integration requires a primary contact, someone to deal with the bug reports submitted by oss-fuzz. The email address needs to belong to an established project committer and be associated with a Google account as per [here](https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/). This will provide you with access to ClusterFuzz, crash reports, and fuzzer statistics. More than 1 person can be included. Please let me know who I should include, if anyone.

Ideally, the fuzz tests would live in this repo (jettison) instead of the oss-fuzz repo to better stay in sync with the code. We can create a PR to do that if you are interested.

[Jazzer](https://github.com/CodeIntelligenceTesting/jazzer) is used for fuzzing Java applications. Jazzer is a coverage-guided, in-process fuzzer for the JVM platform developed by Code Intelligence. It is based on libFuzzer and brings many of its instrumentation-powered mutation features to the JVM.
Jazzer has already found a lot of critical bugs in JVM applications.

Please let me know if you have any questions regarding fuzzing or the oss-fuzz integration.

**Comment by vargen** [comment]
Just wanted to check in to see if anyone is interested in receiving bug reports for this project? Just to clarify our position, we have already written the initial fuzz targets and will handle expanding the code coverage further. Also, if you don’t want to host the fuzz targets we create, they can live in the Google oss-fuzz repo. You would simply need to receive emails from Google and address any discovered bugs / vulnerabilities. If you are interested, please let me know an email address I can use. Preferably a google account as that will enable you full access to the oss-fuzz dashboard.

**Comment by coheigea** [comment]
Hi, we're addressing the two open issues at the moment. Are there any other findings that we need to look at?
