### ISSUE TITLE
Incorrect backslash escaping

### ISSUE THREAD

**Issue by siarheibarsukou** [jettison-json/jettison#58]
Hello. We've encountered a problem with escaping after upgrading from 1.5.1 to 1.5.2. The case `"\\"` is converted into `\"\\\\"` which is not a valid JSON. As far as I can see the issue comes from the new logic added at JSONObject.quote(String string, boolean escapeForwardSlashAlways), lines 1044-1049.

**Comment by coheigea** [comment]
Can you submit a simple test-case please?

**Comment by coheigea** [comment]
Fixed by https://github.com/jettison-json/jettison/commit/631c21e9c467c310a22f5276a2ee0f1aa65359ce
